
/jackal1:
    network:
        publisher_end_point: "tcp://192.168.0.99:3001"
/jackal2:
    network:
        publisher_end_point: "tcp://192.168.0.99:3002"
# /jackal3:
#     network:
#         publisher_end_point: "tcp://192.168.0.99:3003"


    